"""Migration: ``rag_query_traces`` — persist the full prod diagnostics trace.

Ananth invariant (2026-07-19, via EVAL): "anything shown to the user must be
persisted." The per-query SUMMARY row (rag_query_decisions) is lean by
design; the FULL reason→act→observe→decide drill-down the user sees was
ephemeral for prod (only eval runs kept full_response in rag_eval_results).
This table is the trace half; chat owns the rendered-card half.

Design (DB agent, storage owner):

PLACEMENT — separate 1:1 table in the same mobius_rag DB (EVAL's rec,
accepted): keeps the decision row lean for the bandit's index-only hot path;
the trace is large, display-only, and fetched rarely (drill-down clicks).

PRIMARY KEY — ``decision_id`` (= rag_query_decisions.id), NOT correlation_id
as first proposed: correlation_id is NULL on eval rows and REPEATS on
fan-out turns (router-v2 reformulate = N corpus_search calls per chat turn),
so it cannot key a 1:1 relation. decision_id is the true 1:1, is already
client-generated by the writer, and enables a real same-DB FK with ON DELETE
CASCADE (decision row gone → trace gone; never orphaned display data).
Drill-down fetches by correlation_id via the partial index and may get
SEVERAL traces for one turn — consumers order by ts.

RETENTION — KEEP-ALL for now, mechanism ready. Volume math: a full
corpus_search response runs ~20–100KB of jsonb (TOAST-compressed on disk);
at current dev traffic (≤1k queries/day) that is ≤~50MB/day worst case,
realistically far less. The invariant forbids sampling ("anything shown"),
so no sampling. Trip-wire: revisit when the table passes ~5GB
(pg_total_relation_size) — options then are age-window deletion (only if
chat's rendered-card copy satisfies the invariant alone) or cold export.
The (ts) index below exists for exactly that future sweep.

WRITE CONTRACT (RAG's writer — identical to rag_query_decisions):
fire-and-forget background task off the serve path; decision_id is the SAME
client-generated uuid used for the decision row; INSERT ... ON CONFLICT
(decision_id) DO NOTHING; one shared pool. Write the trace row AFTER the
decision row commits (FK ordering).

Idempotent — safe to re-run.
"""
import asyncio
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

import asyncpg
from app.config import DATABASE_URL


_DDL = [
    """
    CREATE TABLE IF NOT EXISTS public.rag_query_traces (
        decision_id    UUID PRIMARY KEY
                       REFERENCES public.rag_query_decisions(id) ON DELETE CASCADE,
        ts             TIMESTAMPTZ NOT NULL DEFAULT now(),
        correlation_id TEXT,                  -- chat turn (repeats on fan-out; NULL on eval)
        is_prod        BOOLEAN NOT NULL DEFAULT false,
        corpus_version BIGINT,                -- from corpus_state (cached read)
        full_response  JSONB NOT NULL         -- complete corpus_search response
    );
    """,
    # Drill-down entry point: turn -> its trace(s).
    """
    CREATE INDEX IF NOT EXISTS idx_rqt_correlation
        ON rag_query_traces (correlation_id)
        WHERE correlation_id IS NOT NULL;
    """,
    # Retention sweeps / recent-first admin reads.
    "CREATE INDEX IF NOT EXISTS idx_rqt_ts ON rag_query_traces (ts DESC);",

    # ── PHI-ADJACENT HARDENING (2026-07-19, EVAL flag: raw query + llm_answer
    #    can carry PHI — chunks are ingest-gated, query/answer are not).
    #    Ruling-independent controls applied immediately; the write gate
    #    (HIPAA-mode vs classify-and-mask) + any phi_masked/phi_flag columns
    #    await the PHI agent's ruling and will amend this migration. ──
    # Tamper-proof, NOT delete-proof (deliberately different from
    # hipaa_analysis_log): UPDATE is blocked — a stored trace can never be
    # edited after the fact — but DELETE stays open because (a) the FK
    # cascade from rag_query_decisions must work (eval-run cleanup), and
    # (b) for PHI-adjacent content, deletability under retention policy is
    # data-minimization, a feature. The audit log is the evidence record;
    # this is the display record.
    """
    CREATE OR REPLACE FUNCTION public.rqt_no_update() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'rag_query_traces rows are immutable once written (PHI-adjacent trace)';
    END $$ LANGUAGE plpgsql;
    """,
    "DROP TRIGGER IF EXISTS trg_rqt_no_update ON public.rag_query_traces;",
    """
    CREATE TRIGGER trg_rqt_no_update
        BEFORE UPDATE ON public.rag_query_traces
        FOR EACH ROW EXECUTE FUNCTION public.rqt_no_update();
    """,
    # Fail-safe access posture until the PHI ruling defines the role model:
    # nothing implicit; readers get explicit grants when ruled.
    "REVOKE ALL ON public.rag_query_traces FROM PUBLIC;",

    # ── PHI RULING APPLIED (2026-07-19): PHI-FREE BY CONSTRUCTION ──
    # The write path scrubs PHI fail-closed (RAG wires PHI's /redact before
    # INSERT), so this is a diagnostics store, not compliance-of-record.
    # Control tier: RESTRICTED READ (minimum-necessary) + NORMAL WRITE.
    # The UPDATE-block trigger above is KEPT as belt-and-braces (traces are
    # write-once; no ruling requires it, nothing is hurt by it).
    # phi_flag + evidence_categories are populated by RAG from the /redact
    # response — CATEGORY LABELS ONLY, never values (name matches
    # hipaa_analysis_log's column per the established identifiers_found→
    # evidence_categories mapping, so cross-table tooling sees one name).
    "ALTER TABLE public.rag_query_traces ADD COLUMN IF NOT EXISTS phi_flag BOOLEAN;",
    ("ALTER TABLE public.rag_query_traces "
     "ADD COLUMN IF NOT EXISTS evidence_categories TEXT[] NOT NULL DEFAULT '{}';"),
    """
    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mobius_trace_writer') THEN
            CREATE ROLE mobius_trace_writer NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mobius_trace_ro') THEN
            CREATE ROLE mobius_trace_ro NOLOGIN;
        END IF;
    END $$;
    """,
    "GRANT INSERT ON public.rag_query_traces TO mobius_trace_writer;",
    "GRANT SELECT ON public.rag_query_traces TO mobius_trace_ro;",

    # ── RETENTION MECHANISM (PHI ruling on deletability, 2026-07-19):
    #    DELETE only via the bounded, logged, automated prune — never ad-hoc
    #    per-row (the display store must not become a quiet selective-erase
    #    surface). Enforced STRUCTURALLY: the delete trigger allows a row
    #    delete only when (a) it is an FK-cascade action (pg_trigger_depth()
    #    > 0 — eval-run cleanup keeps working), or (b) the session-local
    #    prune flag is set, which only rqt_retention_prune() does. The
    #    window defaults to 90 days (PHI's suggestion; exact value is a
    #    pending Ananth business input — parameterized). The 5GB trip-wire
    #    remains the secondary guard. Every prune run logs a row. ──
    """
    CREATE TABLE IF NOT EXISTS public.rqt_prune_log (
        id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        pruned_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        window_used  INTERVAL NOT NULL,
        rows_deleted BIGINT NOT NULL,
        run_by       TEXT NOT NULL DEFAULT current_user
    );
    """,
    """
    CREATE OR REPLACE FUNCTION public.rqt_guard_delete() RETURNS trigger AS $$
    BEGIN
        IF pg_trigger_depth() > 1
           OR current_setting('mobius.rqt_retention_prune', true) = 'on' THEN
            RETURN OLD;
        END IF;
        RAISE EXCEPTION 'rag_query_traces rows are deleted only by the bounded retention prune (rqt_retention_prune) or FK cascade';
    END $$ LANGUAGE plpgsql;
    """,
    "DROP TRIGGER IF EXISTS trg_rqt_guard_delete ON public.rag_query_traces;",
    """
    CREATE TRIGGER trg_rqt_guard_delete
        BEFORE DELETE ON public.rag_query_traces
        FOR EACH ROW EXECUTE FUNCTION public.rqt_guard_delete();
    """,
    """
    CREATE OR REPLACE FUNCTION public.rqt_retention_prune(window_arg INTERVAL DEFAULT '90 days')
    RETURNS BIGINT
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
    AS $$
    DECLARE n BIGINT;
    BEGIN
        IF window_arg < INTERVAL '7 days' THEN
            RAISE EXCEPTION 'retention window below 7-day floor (got %)', window_arg;
        END IF;
        PERFORM set_config('mobius.rqt_retention_prune', 'on', true);  -- txn-local
        DELETE FROM public.rag_query_traces WHERE ts < now() - window_arg;
        GET DIAGNOSTICS n = ROW_COUNT;
        INSERT INTO public.rqt_prune_log (window_used, rows_deleted) VALUES (window_arg, n);
        PERFORM set_config('mobius.rqt_retention_prune', 'off', true);
        RETURN n;
    END $$;
    """,
    """
    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='mobius_trace_pruner') THEN
            CREATE ROLE mobius_trace_pruner NOLOGIN;
        END IF;
    END $$;
    """,
    "REVOKE ALL ON FUNCTION public.rqt_retention_prune(INTERVAL) FROM PUBLIC;",
    "GRANT EXECUTE ON FUNCTION public.rqt_retention_prune(INTERVAL) TO mobius_trace_pruner;",
    "REVOKE ALL ON public.rqt_prune_log FROM PUBLIC;",
    "GRANT SELECT ON public.rqt_prune_log TO mobius_trace_ro;",
]


async def migrate():
    url = DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://")
    conn = await asyncpg.connect(url)
    try:
        for ddl in _DDL:
            await conn.execute(ddl)
        print(f"  Applied {len(_DDL)} DDL statements — rag_query_traces + 2 indexes")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(migrate())
    print("Migration add_rag_query_traces completed.")
