"""Migration: ``rag_query_traces`` — persist the full prod diagnostics trace.

Ananth invariant (2026-07-19, via EVAL): "anything shown to the user must be
persisted." The per-query SUMMARY row (rag_query_decisions) is lean by
design; the FULL reason→act→observe→decide drill-down the user sees was
ephemeral for prod (only eval runs kept full_response in rag_eval_results).
This table is the trace half; chat owns the rendered-card half.

Design (DB agent, storage owner):

PLACEMENT — separate 1:1 table in the same mobius_rag DB (EVAL's rec,
accepted): keeps the decision row lean for the bandit's index-only hot path;
the trace is large, display-only, and fetched rarely (drill-down clicks).

PRIMARY KEY — ``decision_id`` (= rag_query_decisions.id), NOT correlation_id
as first proposed: correlation_id is NULL on eval rows and REPEATS on
fan-out turns (router-v2 reformulate = N corpus_search calls per chat turn),
so it cannot key a 1:1 relation. decision_id is the true 1:1, is already
client-generated by the writer, and enables a real same-DB FK with ON DELETE
CASCADE (decision row gone → trace gone; never orphaned display data).
Drill-down fetches by correlation_id via the partial index and may get
SEVERAL traces for one turn — consumers order by ts.

RETENTION — KEEP-ALL for now, mechanism ready. Volume math: a full
corpus_search response runs ~20–100KB of jsonb (TOAST-compressed on disk);
at current dev traffic (≤1k queries/day) that is ≤~50MB/day worst case,
realistically far less. The invariant forbids sampling ("anything shown"),
so no sampling. Trip-wire: revisit when the table passes ~5GB
(pg_total_relation_size) — options then are age-window deletion (only if
chat's rendered-card copy satisfies the invariant alone) or cold export.
The (ts) index below exists for exactly that future sweep.

WRITE CONTRACT (RAG's writer — identical to rag_query_decisions):
fire-and-forget background task off the serve path; decision_id is the SAME
client-generated uuid used for the decision row; INSERT ... ON CONFLICT
(decision_id) DO NOTHING; one shared pool. Write the trace row AFTER the
decision row commits (FK ordering).

Idempotent — safe to re-run.
"""
import asyncio
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

import asyncpg
from app.config import DATABASE_URL


_DDL = [
    """
    CREATE TABLE IF NOT EXISTS public.rag_query_traces (
        decision_id    UUID PRIMARY KEY
                       REFERENCES public.rag_query_decisions(id) ON DELETE CASCADE,
        ts             TIMESTAMPTZ NOT NULL DEFAULT now(),
        correlation_id TEXT,                  -- chat turn (repeats on fan-out; NULL on eval)
        is_prod        BOOLEAN NOT NULL DEFAULT false,
        corpus_version BIGINT,                -- from corpus_state (cached read)
        full_response  JSONB NOT NULL         -- complete corpus_search response
    );
    """,
    # Drill-down entry point: turn -> its trace(s).
    """
    CREATE INDEX IF NOT EXISTS idx_rqt_correlation
        ON rag_query_traces (correlation_id)
        WHERE correlation_id IS NOT NULL;
    """,
    # Retention sweeps / recent-first admin reads.
    "CREATE INDEX IF NOT EXISTS idx_rqt_ts ON rag_query_traces (ts DESC);",
]


async def migrate():
    url = DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://")
    conn = await asyncpg.connect(url)
    try:
        for ddl in _DDL:
            await conn.execute(ddl)
        print(f"  Applied {len(_DDL)} DDL statements — rag_query_traces + 2 indexes")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(migrate())
    print("Migration add_rag_query_traces completed.")
